version: '2'
services:
  web:
    image: olafrv/proxy:latest
    build:
     context: .
     dockerfile: Dockerfile
    container_name: proxy
    restart: unless-stopped
    networks:
      - composed
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/lib/docker-compose/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/docker-compose/proxy/nginx-app.conf:/etc/nginx/nginx-app.conf:ro
      - /var/lib/docker-compose/proxy/nginx-app-ssl.conf:/etc/nginx/nginx-app-ssl.conf:ro
# Let's Encrypts need rw access to create public challenge folder
#      - /var/lib/docker-compose/proxy/html:/usr/share/nginx/html:ro
      - /var/lib/docker-compose/proxy/letsencrypt/etc:/etc/letsencrypt:rw
      - /var/lib/docker-compose/proxy/letsencrypt/lib:/var/lib/letsencrypt:rw
      - /var/lib/docker-compose/proxy/letsencrypt/log:/var/log/letsencrypt:rw

networks:
  composed:
    external:
      name: composed
