version: '2'
services:
  web:
    image: olafrv/proxy:lastest
    container_name: proxy
    restart: always
    networks:
      - proxy
    ports:
      - 8080:8080
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./html:/usr/share/nginx/html:ro

networks:
  proxy:
    external:
      name: proxy
  
